### ISSUE TITLE
cat /dev/random | slacktee.sh

### ISSUE THREAD

**Issue by MxLinux** [course-hero/slacktee#26]
Makes the script very unhappy.

**Comment by Chikashi-Kato** [comment]
Thank you for bringing up this interesting issue.
I think this is tough to handle in `slacktee.sh` because `cat /dev/random` returns invalid characters too. 
Since `slacktee.sh` is expecting that all of the input are valid strings (currently, it doesn't support binary data), it crushes `slacktee.sh`. 
Since `-f` option stores all of the input to the file and uploads it to Slack, it may be able to handle `cat /dev/random`. However, `cat /dev/random` outputs data infinitely, so `slacktee.sh` waits it forever and cannot upload the result file, I guess.

Do you have any suggestions to handle this issue?

**Comment by Chikashi-Kato** [comment]
I'm closing this issue as `won't fix`, but please feel free to let me know, if you think we should handle this issue somehow. I'm looking forward to hearing your suggestions!!
