### ISSUE TITLE
Change slacktee.sh command to only slacktee when installing

### ISSUE THREAD

**Issue by iknite** [course-hero/slacktee#30]
What do you think?
I'm used to change it as a difference between custom/local scripts to installed tools.

In any case that's a really useful script, :beers:

**Comment by jimsmith** [comment]
Leave it 'as is' as it's a Bash script after all and the .sh identifies it as such for sysadmins, operations and TechOps/DevOps engineers.

**Comment by Chikashi-Kato** [comment]
Hi knite and jimsmith, 

First of all, thank you for using slacktee and sharing your thoughts about it!
I also would prefer to leave it as-is. As jimsmith mentioned, slacktee has good amount of users and it's already integrated with their systems. So, I would like to avoid an unnecessary confusion caused by changing the file name.

One idea is adding another command line option to `install.sh` which allows us to change the file name when it's installed. 
This change doesn't change any default behaviors, but it adds a little bit more flexibility. 
What do you think?

**Comment by iknite** [comment]
It will be nice indeed, let me try to find a moment in this weekend to make a PR
Thanks again!

**Comment by Chikashi-Kato** [comment]
Cool! Looking forward to seeing your PR :)
