### ISSUE TITLE
slacktee install as root

### ISSUE THREAD

**Issue by cheesemarathon** [course-hero/slacktee#36]
Ive spent several days trying to get slacktee to work with the root crontab. I installed it as per the instructions in the readme. I also included all the path variables i could think of in the crontab, however it did not work. When i looked in slacktee.sh i noticed there was no webhook url set. So i set it in there and it worked. So it seems that sudo cron jobs cant read the config in my home directory. Not sure if there is a better way to fix this?

**Comment by Chikashi-Kato** [comment]
Thank you for using slacktee, cheesemarathon!

If slacktee is executed by the root user, slacktee tries to read the configuration file `.slacktee` from the home directory of the root user, not from your user's home directory. So, please try to copy your `.slacktee` file to root user's home directory. You should be able to find the directory of the root user in `/etc/passwd`.

Also, you can use the server-wide configuration. Since slacktee also tries to read the configuration file `/etc/slacktee.conf`, by creating the file, all of the users on the server can use the same configuration. You can find the sample file in this GitHub repo.
If both configuration files, `/etc/slacktee.conf` and `~/.slacktee`, exist, slacktee prioritizes `~/.slacktee`, therefore users can overwrite the server-wide configuration if they want. 

I hope this information helps to setup slacktee!

**Comment by Chikashi-Kato** [comment]
I closed this issue, but please feel free to leave a commend if you have any questions!
